### ISSUE TITLE
How to provide className regardless?

### ISSUE THREAD

**Issue by morgs32** [royriojas/css-local-loader#1]
Hi @royriojas I came upon this and have a question for you? Do you think it would be possible with a proxy like this to provide the requested classname even if it DOESN'T exist?

**Comment by royriojas** [comment]
yes it is possible, but by design is discouraged in this loader. 

But in that case the default `classnames` utility is enough as it does actually that, this loader won't be needed for that.

```js
import classnames from 'classnames/bind';
import styles from './styles.less';

const cx = classnames.bind(styles);

const cNames = cx('local', 'orGlobalClass'); // local_xa23121 orGlobalClass
```

**Comment by morgs32** [comment]
Interrrrresting! But I wish I could keep the `localIdentName` naming conventions. Like "[name]__[local]" for example. Thoughts?

**Comment by royriojas** [comment]
@morgs32, not sure I follow your question, can you provide an example of what you want to accomplish?

**Comment by morgs32** [comment]
My situation is something like this:

`Navbar.less`:
```
.foo {
  background: red;
}
```

`Navbar.js`:
```
import classnames from 'classnames/bind';
import styles from './Navbar.less';
const cx = classnames.bind(styles);
const cNames = cx('foo', 'bar'); // Navbar__foo Navbar__bar
```

And I'm using webpack's css-loader: https://github.com/webpack-contrib/css-loader

So that's how I get `Navbar__foo` from `styles.foo`. By setting `localIdentName` to `[name]__[local]`

But what I'm trying to achieve is the ability for someone to add their own global stylesheet, looking at my rendered components for the appropriate classnames.

So someone could embed:
<link href="..../styles.css">

With 
```
.Navbar__foo {
  background: blue;
}
```

And that way overwrite the css I make in compilation...

Hopefully this is clearer? Thanks for you advice!

**Comment by morgs32** [comment]
All of this was a putrid code smell in the first place!
